services:
  - docker

script:
  # Build
  - echo '========= Start bulding ========='
  - docker build -t udagram-api-feed:v0 ./udagram-api-feed
  - docker build -t udagram-api-user:v0 ./udagram-api-user
  - docker build -t udagram-frontend:v0 ./udagram-frontend
  - docker build -t udagram-reverseproxy:v0 ./udagram-reverseproxy

  # Tagging
  - echo '========= Start tagging ========='
  - docker tag udagram-api-feed:v0 vrykolakas16/udagram-api-feed:v0
  - docker tag udagram-api-user:v0 vrykolakas16/udagram-api-user:v0
  - docker tag udagram-frontend:v0 vrykolakas16/udagram-frontend:v0
  - docker tag udagram-reverseproxy:v0 vrykolakas16/udagram-reverseproxy:v0

  - echo '========= Docker Image LS ========='
  - docker image ls

after_success:
  # Login Docker
  - echo '========= Docker Image LS ========='
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

  # Pushing
  - echo '========= Start pushing image ========='
  - docker push vrykolakas16/udagram-api-feed:v0
  - docker push vrykolakas16/udagram-api-user:v0
  - docker push vrykolakas16/udagram-frontend:v0
  - docker push vrykolakas16/udagram-reverseproxy:v0